package com.example.ivenglish

import android.annotation.SuppressLint
import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import android.widget.EditText
import android.widget.TextView

class QuizActivity : AppCompatActivity() {
    var allList = ArrayList<Quiz>()
    var quizList = ArrayList<Quiz>()
    var numberOfGoodAnswers: Int = 0
    var actualQuiz: Int = 0
    var sizeOfQuiz: Int = 20

    @SuppressLint("SetTextI18n")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_quiz)
    
        this.allList.add(Quiz("(se) réveiller", "to awake", "awoke", "awoken"))
        this.allList.add(Quiz("supporter", "to bear", "bore", "borne"))
        this.allList.add(Quiz("battre", "to beat", "beat", "beaten"))
        this.allList.add(Quiz("devenir", "to become", "became", "become"))
        this.allList.add(Quiz("commencer", "to begin", "began", "begun"))
        this.allList.add(Quiz("(se) courber", "to bend", "bent", "bent"))
        this.allList.add(Quiz("parier", "to bet", "bet", "bet"))
        this.allList.add(Quiz("offrir (un prix)", "to bid", "bid", "bid"))
        this.allList.add(Quiz("lier, relier", "to bind", "bound", "bound"))
        this.allList.add(Quiz("mordre", "to bite", "bit", "bitten"))
        this.allList.add(Quiz("saigner", "to bleed", "bled", "bled"))
        this.allList.add(Quiz("souffler", "to blow", "blew", "blown"))
        this.allList.add(Quiz("casser", "to break", "broke", "broken"))
        this.allList.add(Quiz("élever (du bétail)", "to breed", "bred", "bred"))
        this.allList.add(Quiz("apporter", "to bring", "brought", "brought"))
        this.allList.add(Quiz("construire", "to build", "built", "built"))
        this.allList.add(Quiz("brûler", "to burn", "burnt", "burnt"))
        this.allList.add(Quiz("éclater", "to burst", "burst", "burst"))
        this.allList.add(Quiz("acheter", "to buy", "bought", "bought"))
        this.allList.add(Quiz("jeter", "to cast", "cast", "cast"))
        this.allList.add(Quiz("attraper", "to catch", "caught", "caught"))
        this.allList.add(Quiz("choisir", "to choose", "chose", "chosen"))
        this.allList.add(Quiz("s'accrocher", "to cling", "clung", "clung"))
        this.allList.add(Quiz("venir", "to come", "came", "come"))
        this.allList.add(Quiz("coûter", "to cost", "cost", "cost"))
        this.allList.add(Quiz("ramper", "to creep", "crept", "crept"))
        this.allList.add(Quiz("couper", "to cut", "cut", "cut"))
        this.allList.add(Quiz("distribuer", "to deal", "dealt", "dealt"))
        this.allList.add(Quiz("creuser", "to dig", "dig", "dig"))
        this.allList.add(Quiz("faire", "to do", "did", "done"))
        this.allList.add(Quiz("dessiner", "to draw", "drew", "drawn"))
        this.allList.add(Quiz("rêver", "to dream", "dreamt", "dreamt"))
        this.allList.add(Quiz("boire", "to drink", "drank", "drunk"))
        this.allList.add(Quiz("conduire", "to drive", "drove", "driven"))
        this.allList.add(Quiz("habiter", "to dwell", "dwelt", "dwelt"))
        this.allList.add(Quiz("manger", "to eat", "ate", "eaten"))
        this.allList.add(Quiz("tomber", "to fall", "fell", "fallen"))
        this.allList.add(Quiz("nourrir", "to feed", "fed", "fed"))
        this.allList.add(Quiz("sentir, éprouver", "to feel", "felt", "felt"))
        this.allList.add(Quiz("combattre", "to fight", "fought", "fought"))
        this.allList.add(Quiz("trouver", "to find", "found", "found"))
        this.allList.add(Quiz("s'enfuir", "to flee", "fled", "fled"))
        this.allList.add(Quiz("jeter violemment", "to fling", "flung", "flung"))
        this.allList.add(Quiz("voler", "to fly", "flew", "flown"))
        this.allList.add(Quiz("interdire", "to forbid", "forbade", "forbidden"))
        this.allList.add(Quiz("oublier", "to forget", "forgot", "forgotten"))
        this.allList.add(Quiz("pardonner", "to forgive", "forgave", "forgiven"))
        this.allList.add(Quiz("geler", "to freeze", "froze", "frozen"))
        this.allList.add(Quiz("obtenir", "to get", "got", "got"))
        this.allList.add(Quiz("donner", "to give", "gave", "given"))
        this.allList.add(Quiz("aller", "to go", "went", "gone"))
        this.allList.add(Quiz("moudre", "to grind", "ground", "ground"))
        this.allList.add(Quiz("grandir", "to grow", "grew", "grown"))
        this.allList.add(Quiz("pendre, accrocher", "to hang", "hung", "hung"))
        this.allList.add(Quiz("avoir", "to have", "had", "had"))
        this.allList.add(Quiz("entendre", "to hear", "heard", "heard"))
        this.allList.add(Quiz("(se) cacher", "to hide", "hid", "hidden"))
        this.allList.add(Quiz("frapper, atteindre", "to hit", "hit", "hit"))
        this.allList.add(Quiz("tenir", "to hold", "held", "held"))
        this.allList.add(Quiz("blesser", "to hurt", "hurt", "hurt"))
        this.allList.add(Quiz("garder", "to keep", "kept", "kept"))
        this.allList.add(Quiz("s'agenouiller", "to kneel", "knelt", "knelt"))
        this.allList.add(Quiz("savoir, connaître", "to know", "knew", "known"))
        this.allList.add(Quiz("poser à plat", "to lay", "laid", "laid"))
        this.allList.add(Quiz("mener", "to lead", "led", "led"))
        this.allList.add(Quiz("s'appuyer", "to lean", "leant", "leant"))
        this.allList.add(Quiz("sauter", "to leap", "leapt", "leapt"))
        this.allList.add(Quiz("apprendre", "to learn", "learnt", "learnt"))
        this.allList.add(Quiz("laisser, quitter", "to leave", "left", "left"))
        this.allList.add(Quiz("prêter", "to lend", "lent", "lent"))
        this.allList.add(Quiz("permettre, louer", "to let", "let", "let"))
        this.allList.add(Quiz("être étendu", "to lie", "lay", "lain"))
        this.allList.add(Quiz("allumer", "to light", "lit", "lit"))
        this.allList.add(Quiz("perdre", "to lose", "lost", "lost"))
        this.allList.add(Quiz("faire, fabriquer", "to make", "made", "made"))
        this.allList.add(Quiz("signifier", "to mean", "meant", "meant"))
        this.allList.add(Quiz("(se) rencontrer", "to meet", "met", "met"))
        this.allList.add(Quiz("payer", "to pay", "paid", "paid"))
        this.allList.add(Quiz("mettre", "to put", "put", "put"))
        this.allList.add(Quiz("cesser (de)", "to quit", "quit", "quit"))
        this.allList.add(Quiz("lire", "to read", "read", "read"))
        this.allList.add(Quiz("(se) débarrasser", "to rid", "rid", "rid"))
        this.allList.add(Quiz("chevaucher", "to ride", "rode", "ridden"))
        this.allList.add(Quiz("sonner", "to ring", "rang", "rung"))
        this.allList.add(Quiz("s'élever, se lever", "to rise", "rose", "risen"))
        this.allList.add(Quiz("courir", "to run", "ran", "run"))
        this.allList.add(Quiz("scier", "to saw", "sawed", "sawn"))
        this.allList.add(Quiz("dire", "to say", "said", "said"))
        this.allList.add(Quiz("voir", "to see", "saw", "seen"))
        this.allList.add(Quiz("chercher", "to seek", "sought", "sought"))
        this.allList.add(Quiz("vendre", "to sell", "sold", "sold"))
        this.allList.add(Quiz("envoyer", "to send", "sent", "sent"))
        this.allList.add(Quiz("fixer", "to set", "set", "set"))
        this.allList.add(Quiz("coudre", "to sew", "sewed", "sewn"))
        this.allList.add(Quiz("secouer", "to shake", "shook", "shaken"))
        this.allList.add(Quiz("tondre (des moutons)", "to shear", "sheared", "shorn"))
        this.allList.add(Quiz("verser (des larmes)", "to shed", "shed", "shed"))
        this.allList.add(Quiz("briller", "to shine", "shone", "shone"))
        this.allList.add(Quiz("ferrer, chausser", "to shoe", "shod", "shod"))
        this.allList.add(Quiz("tirer", "to shoot", "shot", "shot"))
        this.allList.add(Quiz("montrer", "to show", "showed", "shown"))
        this.allList.add(Quiz("retrécir", "to shrink", "shrank", "shrunk"))
        this.allList.add(Quiz("fermer", "to shut", "shut", "shut"))
        this.allList.add(Quiz("chanter", "to sing", "sang", "sung"))
        this.allList.add(Quiz("couler", "to sink", "sank", "sunk"))
        this.allList.add(Quiz("être assis", "to sit", "sat", "sat"))
        this.allList.add(Quiz("dormir", "to sleep", "slept", "slept"))
        this.allList.add(Quiz("glisser", "to slide", "slid", "slid"))
        this.allList.add(Quiz("lancer (avec force)", "to sling", "slung", "slung"))
        this.allList.add(Quiz("aller furtivement", "to slink", "slunk", "slunk"))
        this.allList.add(Quiz("fendre, inciser", "to slit", "slit", "slit"))
        this.allList.add(Quiz("sentir (odorat)", "to smell", "smelt", "smelt"))
        this.allList.add(Quiz("semer", "to sow", "sowed", "sown"))
        this.allList.add(Quiz("parler", "to speak", "spoke", "spoken"))
        this.allList.add(Quiz("aller à toute vitesse", "to speed", "sped", "sped"))
        this.allList.add(Quiz("épeler", "to spell", "spelt", "spelt"))
        this.allList.add(Quiz("dépenser", "to spend", "spent", "spent"))
        this.allList.add(Quiz("renverser (un liquide)", "to spill", "spilt", "spilt"))
        this.allList.add(Quiz("cracher", "to spit", "spat", "spat"))
        this.allList.add(Quiz("fendre", "to split", "split", "split"))
        this.allList.add(Quiz("gâcher, gâter", "to spoil", "spoilt", "spoilt"))
        this.allList.add(Quiz("répandre", "to spread", "spread", "spread"))
        this.allList.add(Quiz("jaillir, bondir", "to spring", "sprang", "sprung"))
        this.allList.add(Quiz("être debout", "to stand", "stood", "stood"))
        this.allList.add(Quiz("voler, dérober", "to steal", "stole", "stolen"))
        this.allList.add(Quiz("coller", "to stick", "stuck", "stuck"))
        this.allList.add(Quiz("piquer", "to sting", "stung", "stung"))
        this.allList.add(Quiz("puer", "to stink", "stank", "stunk"))
        this.allList.add(Quiz("marcher à grand pas", "to stride", "strode", "stridden"))
        this.allList.add(Quiz("frapper", "to strike", "struck", "struck"))
        this.allList.add(Quiz("enfiler, tendre (une corde)", "to string", "strung", "strung"))
        this.allList.add(Quiz("s'efforcer", "to strive", "strove", "striven"))
        this.allList.add(Quiz("jurer", "to swear", "swore", "sworn"))
        this.allList.add(Quiz("balayer", "to sweep", "swept", "swept"))
        this.allList.add(Quiz("enfler", "to swell", "swelled", "swollen"))
        this.allList.add(Quiz("nager", "to swim", "swam", "swum"))
        this.allList.add(Quiz("se balancer", "to swing", "swung", "swung"))
        this.allList.add(Quiz("prendre", "to take", "took", "taken"))
        this.allList.add(Quiz("enseigner", "to teach", "taught", "taught"))
        this.allList.add(Quiz("déchirer", "to tear", "tore", "torn"))
        this.allList.add(Quiz("dire, raconter", "to tell", "told", "told"))
        this.allList.add(Quiz("penser", "to think", "thought", "thought"))
        this.allList.add(Quiz("jeter", "to throw", "threw", "thrown"))
        this.allList.add(Quiz("enfoncer", "to thrust", "thrust", "thrust"))
        this.allList.add(Quiz("fouler aux pieds", "to tread", "trod", "trodden"))
        this.allList.add(Quiz("comprendre", "to understand", "understood", "understood"))
        this.allList.add(Quiz("(se) réveiller", "to wake", "woke", "woken"))
        this.allList.add(Quiz("porter (des vêtements)", "to wear", "wore", "worn"))
        this.allList.add(Quiz("tisser", "to weave", "wove", "woven"))
        this.allList.add(Quiz("pleurer", "to weep", "wept", "wept"))
        this.allList.add(Quiz("gagner", "to win", "won", "won"))
        this.allList.add(Quiz("enrouler", "to wind", "wound", "wound"))
        this.allList.add(Quiz("tordre", "to wring", "wrung", "wrung"))
        this.allList.add(Quiz("écrire", "to write", "wrote", "wrote"))

        for (x in 1..this.sizeOfQuiz){
            this.quizList.add(allList.random())
        }

        val cueTextView = findViewById<TextView>(R.id.cue)
        val scoreTextView = findViewById<TextView>(R.id.score)
        val turnTextView = findViewById<TextView>(R.id.turn)

        cueTextView.text = quizList[this.actualQuiz].translation
        scoreTextView.text = "Score : "  + this.numberOfGoodAnswers.toString() + " / " + this.actualQuiz.toString()
        turnTextView.text = "Turn "  + (this.actualQuiz + 1).toString() + " / " + this.sizeOfQuiz.toString()
    }

    fun onClickBtnNext(view: View){
        val cueTextView = findViewById<TextView>(R.id.cue)
        val scoreTextView = findViewById<TextView>(R.id.score)
        val turnTextView = findViewById<TextView>(R.id.turn)
        val infinitive: EditText = findViewById(R.id.infinitiveText)
        val preterit: EditText = findViewById(R.id.preteritText)
        val particle: EditText = findViewById(R.id.particleText)
        // Check if the answer is correct
        if (infinitive.text.toString().toLowerCase() == this.quizList[this.actualQuiz].verb
            && preterit.text.toString().toLowerCase() == this.quizList[this.actualQuiz].preterit
            && particle.text.toString().toLowerCase() == this.quizList[this.actualQuiz].pp) {
            this.numberOfGoodAnswers++
        }
        if (this.actualQuiz + 1 == this.sizeOfQuiz) {
            this.end()
        } else {
            // Next quiz
            this.actualQuiz++
            cueTextView.text = this.quizList[this.actualQuiz].translation
            scoreTextView.text = "Score : "  + this.numberOfGoodAnswers.toString() + " / " + this.actualQuiz.toString()
            turnTextView.text = "Turn "  + (this.actualQuiz + 1).toString() + " / " + this.sizeOfQuiz.toString()
            infinitive.setText("")
            preterit.setText("")
            particle.setText("")
        }
    }

    private fun end(){
        val intent = Intent ( this, EndQuiz::class.java)
        intent.putExtra("score", this.numberOfGoodAnswers)
        intent.putExtra("size", this.sizeOfQuiz)
        startActivity(intent)
    }
}
